class PlayerEmojis:
    SHUFFLE_EMOJI = "🔀"
    PREV_EMOJI = "⏪"
    SKIP_EMOJI = "⏩"
    PAUSE_EMOJI = "⏸️"
    PLAY_EMOJI = "▶️"
    STOP_EMOJI = "⏹"
    VOL_UP_EMOJI = "🔊"
    VOL_DOWN_EMOJI = "🔉"
    REPEAT_EMOJI = "🔂"
